defaults:
  - _self_
  - data: custom_10s
  - evaluation: all
  - model: resnet
  - dataloader: five_sec

gpu: -1
gpu_ids: [0, 1, 2]  # gpus to use if multi_gpu==true
multi_gpu: false
num_split: 5
augmentation: false
root_path: "${data.data_root}/"
model_path: "${root_path}models/"
logging_path: "${root_path}logs/"
report_root: "${root_path}reports/"
# report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}.csv"
report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}_${evaluation.subR}.csv"
is_verbose: false

custom_resnet: true
L: 12
num_sensors: 5
