defaults:
  - _self_
  - data: custom_10s
  - evaluation: all
  - model: resnet
  - dataloader: five_sec

gpu: -1
gpu_ids: [0, 1, 2]  # gpus to use if multi_gpu==true
multi_gpu: false
num_split: 5
augmentation: false
root: /Users/kaanbecker/Documents/VSCode/EASE_pretrained_models/ssl_wearables/ssl-wearables
data_name: EASE_30Hz_0.4w_0.2s

# output paths
model_path: "${root}/experiments/${data_name}/models/"
logging_path: "${root}/experiments/${data_name}/logs/"
report_path: "${root}/experiments/${data_name}/reports/"
is_verbose: false

custom_resnet: true
L: 12
num_sensors: 5
